Update docs
Couchbase-Ecosystem/cbl-ionic-docs pull request #14
Opened 2024-05-20 11:31 UTC by azaddhirajkumar

2024-05-20 14:19 UTC, biozal requested changes

2024-05-20 14:19 UTC, biozal commented on docs/Queries/sqlplusplus.md
> +| `&#124&#124` | Concatenating | `SELECT firstName &#124&#124 lastName AS fullName FROM db` |
`SELECT firstName &#124&#124 lastName AS fullName FROM testScope.testCollection`

2024-05-20 14:19 UTC, biozal commented on docs/Queries/sqlplusplus.md
> +FROM db;
FROM testScope.testCollection;

2024-05-20 14:19 UTC, biozal commented on docs/Queries/sqlplusplus.md
> +FROM db;
FROM testScope.testCollection;

2024-05-20 14:19 UTC, biozal commented on docs/database-prebuilt.md
> +const result = await pd.getDefaultPath();
This is wrong.  You don't do anything with the path you get back.  You need to set the database config directory to be the path you got.

```
const path = await pd.getDefaultPath();

// Set database name, source path, and configuration
const dbName = 'my_prebuilt_db';
const sourcePath = await database.getPath();
const config = new DatabaseConfiguration();
config.setDirectory(path);

```

2024-05-20 14:19 UTC, biozal commented on docs/databases.md
> +await db.open();dar
you have a typo here.  The dar isn't needed.

2024-05-20 14:19 UTC, biozal commented on docs/databases.md
> +This is a resource intensive operation and is not performed automatically. It should be run on-demand using the API. If in doubt, consult Couchbase support.
We don't provide support for the Ionic framework.  It's an open source project, so we can't tell them to contact support.  Instead we can direct them to the forums where they can ask questions:

https://www.couchbase.com/forums/

2024-05-20 14:19 UTC, biozal commented on docs/documents.md
> +  const document = await collection.document(change.documentID);
Need to explain that once they don't need the change listener anymore, they must use the token to remove the change listener. It is the developer responsibility to remove change listeners for things like the app going to the background or closing.

```typescript
await collection.removeDocumentChangeListener(token);
```

2024-05-20 14:19 UTC, biozal commented on docs/scopes-collections.md
> +
the code is blank?

2024-05-21 07:47 UTC, azaddhirajkumar commented on docs/scopes-collections.md
> +
I have put it back

2024-05-21 10:30 UTC, azaddhirajkumar commented on docs/databases.md
> +This is a resource intensive operation and is not performed automatically. It should be run on-demand using the API. If in doubt, consult Couchbase support.
Done

2024-05-21 10:31 UTC, azaddhirajkumar commented on docs/databases.md
> +await db.open();dar
done

2024-05-21 10:50 UTC, azaddhirajkumar commented on docs/database-prebuilt.md
> +const result = await pd.getDefaultPath();
correct. missed it.

2024-05-22 06:01 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +const query = database.createQuery("SELECT META().id AS thisId FROM _ WHERE type = \"hotel\"");
Done

2024-05-22 06:01 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +FROM db
Done

2024-05-22 07:00 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +final query = await Query.fromN1ql(
done

2024-05-22 07:04 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +FROM db
done

2024-05-22 08:26 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +FROM db;
done

2024-05-22 08:27 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +FROM db;
done

2024-05-22 09:13 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +SELECT department
done

2024-05-22 09:13 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +SELECT name
done

2024-05-22 09:34 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +with the backticks ` character. For example, to use a hyphen (-) in an
done

2024-05-22 09:36 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +FROM db;
done

2024-05-22 09:36 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +FROM db
done

2024-05-22 09:37 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +FROM db
done

2024-05-22 09:38 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +WHERE middleName IS NULL;
done

2024-05-22 11:15 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +#### Table 1. Example Column Names for SELECT *
created an issue for this #15

2024-05-28 17:38 UTC, biozal requested changes

2024-05-28 17:38 UTC, biozal commented on docs/Queries/live-queries.md
> +In the case of the synchronous API, all changes are delivered to the listeners as soon as they are registered.
There is no synchronous API in Javascript. This is more of the stream vs promise in Dart.  You can remove the entire section of Watching with Change Listeners since there is only one way to listen.

2024-05-28 17:38 UTC, biozal commented on docs/Queries/live-queries.md
> +await query.addChangeListener(async (change) => {
This isn't proper javascript sample code.  Look at the LiveQuery page in the example app for more details of this:

```javascript
const token = await query.addChangeListener((change) => {
  if (change.error !== null && change.error !== undefined) {
    // deal with error...
  } else {
    const results = change.results;
    //loop through ResultSet
    for (const doc of results) {
      //do something with doc                   
    }
  }
});
```

2024-05-28 17:38 UTC, biozal commented on docs/Queries/live-queries.md
> +final token = await query.addChangeListener((change) async { ... });
Again this is dart now TS code.  You would have something along the lines of:

```javascript
const token = await query.addChangeListener((change) => { ... });
await query.removeChangeListener(token);
```

2024-05-28 17:38 UTC, biozal commented on docs/Queries/sqlplusplus.md
> +Here we are accessing the default collection using the shorthand notation (`_`) — see the FROM clause for more on data source selection and Query Parameters for more on parameterized queries.
This line doesn't match the example above and can be removed because you are using the inventory scope and the hotel collection.

2024-05-28 17:38 UTC, biozal commented on docs/blobs.md
> +let document = await collection.document(documentId);
const document = await collection.document(documentId);

2024-05-28 17:38 UTC, biozal commented on docs/databases.md
> +To create or open a database, use the Database class from the cbl-cblite package, specifying the database name and optionally, a DatabaseConfiguration for custom settings like the database directory
it's just cblite not cbl-cblite.

2024-05-28 17:38 UTC, biozal commented on docs/databases.md
> +import { Database, DatabaseConfiguration } from 'cbl-cblite'; //import the package
import { Database, DatabaseConfiguration } from 'cblite'; //import the package

2024-05-28 17:38 UTC, biozal commented on docs/full-text-search.md
> +results.forEach(result => {
you need to use a for loop to loop through the results:

for(const doc of results)

2024-05-28 17:38 UTC, biozal commented on docs/scopes-collections.md
> +const collection = await database.createCollection(collectionName, scopeName);
```javascript
const scopeName = "myScopeName";
const collectionName = "myCollectionName";
const collection = await database.createCollection(collectionName, scopeName);
```

2024-05-29 07:32 UTC, azaddhirajkumar commented on docs/Queries/live-queries.md
> +In the case of the synchronous API, all changes are delivered to the listeners as soon as they are registered.
Done

2024-05-29 07:37 UTC, azaddhirajkumar commented on docs/Queries/live-queries.md
> +await query.addChangeListener(async (change) => {
Done

2024-05-29 07:39 UTC, azaddhirajkumar commented on docs/Queries/live-queries.md
> +final token = await query.addChangeListener((change) async { ... });
Done

2024-05-29 07:40 UTC, azaddhirajkumar commented on docs/Queries/sqlplusplus.md
> +Here we are accessing the default collection using the shorthand notation (`_`) — see the FROM clause for more on data source selection and Query Parameters for more on parameterized queries.
Done

2024-05-29 07:41 UTC, azaddhirajkumar commented on docs/blobs.md
> +let document = await collection.document(documentId);
done

2024-05-29 07:42 UTC, azaddhirajkumar commented on docs/databases.md
> +To create or open a database, use the Database class from the cbl-cblite package, specifying the database name and optionally, a DatabaseConfiguration for custom settings like the database directory
done

2024-05-29 07:49 UTC, azaddhirajkumar commented on docs/scopes-collections.md
> +const collection = await database.createCollection(collectionName, scopeName);
done

2024-05-30 13:33 UTC, merged