Added changes for sync gateway docs
Couchbase-Ecosystem/cbl-ionic-docs pull request #37
Opened 2024-06-19 17:12 UTC by azaddhirajkumar

2024-06-20 14:21 UTC, biozal requested changes

2024-06-20 14:21 UTC, biozal commented on docs/DataSync/remote-sync-gateway.md
> +    * The 1.x replication protocol when a Couchbase Lite 1.x client connects through `http://localhost:4984/db`.
We don't need to talk about Legacy.  This SDK was never available for 1.x.

2024-06-20 14:21 UTC, biozal commented on docs/DataSync/remote-sync-gateway.md
> +const targetURL = 'wss://10.1.1.12:8092/travel-sample';
I don't think this is a good URL example.  That's a custom port and most customers would be running on 4984 or 443

2024-06-20 14:21 UTC, biozal commented on docs/DataSync/remote-sync-gateway.md
> +Use `ReplicatorConfiguration` properties `acceptOnlySelfSignedServerCertificate` and `setPinnedServerCertificate()`, to tell the replicator how to verify server-supplied TLS server certificates.
we don't support setPinnedServerCertificate per Priya's request.   Unless someone begs for it, it's a P3/P4 in the backlog that I don't plan on picking up.

2024-06-20 14:21 UTC, biozal commented on docs/DataSync/remote-sync-gateway.md
> +
remove this section as we don't support Pinned Certificates

2024-06-20 14:21 UTC, biozal commented on docs/DataSync/remote-sync-gateway.md
> +const sessionAuthenticator = new SessionAuthenticator("904ac010862f37c8dd99015a33ab5a3565fd8447");
You will want to look at the code for SessionAuthenticator:  
https://github.com/Couchbase-Ecosystem/cblite-js/blob/main/cblite/src/session-authenticator.ts#L8

Technically speaking we support a cookie name and default it to the default value, but the end user "could" change that in the Sync Gateway configuration, which they would then have to pass in.

2024-06-20 14:21 UTC, biozal commented on docs/DataSync/remote-sync-gateway.md
> +Where necessary, clients can override the default auto-purge behavior. This can be done either by setting enableAutoPurge to false, or for finer control by applying pull-filters — see: Table 4 and Re
We don't support pull filters, so this needs to be removed.

2024-06-20 14:21 UTC, biozal commented on docs/DataSync/remote-sync-gateway.md
> +## Certificate Pinning
Remove Certificate Pinning as stated before we aren't going to support it.

2024-06-21 06:17 UTC, azaddhirajkumar commented on docs/DataSync/remote-sync-gateway.md
> +    * The 1.x replication protocol when a Couchbase Lite 1.x client connects through `http://localhost:4984/db`.
Removed legacy compatibility

2024-06-21 06:21 UTC, azaddhirajkumar commented on docs/DataSync/remote-sync-gateway.md
> +const targetURL = 'wss://10.1.1.12:8092/travel-sample';
Replaced it with 4984 as we are using it in other examples.

2024-06-21 06:35 UTC, azaddhirajkumar commented on docs/DataSync/remote-sync-gateway.md
> +Use `ReplicatorConfiguration` properties `acceptOnlySelfSignedServerCertificate` and `setPinnedServerCertificate()`, to tell the replicator how to verify server-supplied TLS server certificates.
Removed it.

2024-06-21 06:36 UTC, azaddhirajkumar commented on docs/DataSync/remote-sync-gateway.md
> +Where necessary, clients can override the default auto-purge behavior. This can be done either by setting enableAutoPurge to false, or for finer control by applying pull-filters — see: Table 4 and Re
Done

2024-06-21 06:37 UTC, azaddhirajkumar commented on docs/DataSync/remote-sync-gateway.md
> +## Certificate Pinning
done

2024-06-21 07:15 UTC, azaddhirajkumar commented on docs/DataSync/remote-sync-gateway.md
> +const sessionAuthenticator = new SessionAuthenticator("904ac010862f37c8dd99015a33ab5a3565fd8447");
Updated it in comments

2024-06-21 18:02 UTC, merged